# .github/workflows/python-tests.yml
name: Python Tests

on: [push, pull_request]  # Trigger on push and pull request events

jobs:
  test:
    runs-on: ubuntu-latest  # Specify the environment to run the tests

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v2  # Step to pull the repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Python version for the tests

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        pytest tests
